### PR TITLE
fixed MOSI/MISO and channel naming on CH32V003 parts

### PR DESCRIPTION
**Pull request by prosper00**
MOSI and MISO were swapped, and the timer channel naming conventions were inconsistent (some were prefixed with 'Tx', some weren't)

### CODE REVIEW

**Comment by Tengo10** [comment]
I think we should drop the T1 / T2 in favour of just using the label colours to keep it as short as possible

**Comment by prosper00** [comment]
Personally, i had a hard time distinguishing the colors

**Comment by Tengo10** [comment]
What colours would you recommend to make it more legible. With the T1/T2 in front the label size would have to be adjusted and make the whole image even wider

**Comment by prosper00** [comment]
ill play around tomorrow sometime and see if i can propose something

**Comment by prosper00** [comment]
Hmm, on second thought, the colors look fine on my monitor. Must just be my phone screen that's hard to read.

**Review by Tengo10 — APPROVED** [review]

**Pull request merged**
